import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import linregress

# Set scientific plotting style for journal submission
plt.rcParams.update({
    'font.family': 'serif',
    'font.size': 12,
    'axes.labelsize': 14,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'legend.fontsize': 12,
    'figure.dpi': 300
})

def plot_finite_size_scaling():
    # 1. Load the data generated by the C++ engine
    try:
        df = pd.read_csv('../data/dynamic_finite_size_scaling.csv')
    except FileNotFoundError:
        print("Error: Could not find 'dynamic_finite_size_scaling.csv'.")
        return

    # 2. Calculate the inverse lattice size (1/L) for the x-axis
    df['1_over_L'] = 1.0 / df['L']

    # 3. Perform linear regression to extrapolate to the thermodynamic limit
    slope, intercept, r_value, p_value, std_err = linregress(df['1_over_L'], df['Avg_Critical_H0'])

    # 4. Create the plot
    fig, ax = plt.subplots(figsize=(8, 6))

    # FIX 1: Add error bars to represent the 0.2 step-size resolution
    ax.errorbar(df['1_over_L'], df['Avg_Critical_H0'], yerr=0.2,
                fmt='o', color='black', ecolor='black', capsize=5,
                markersize=10, zorder=3, label='Monte Carlo Data')

    # Plot the extrapolation line back to the y-axis
    x_fit = np.linspace(0, max(df['1_over_L']) * 1.1, 100)
    y_fit = slope * x_fit + intercept
    ax.plot(x_fit, y_fit, '--', color='red', linewidth=2, zorder=2,
            label=f'Extrapolation ($L \\to \\infty$)\n$H_c(\\infty) \\approx {intercept:.3f}$')

    # 5. Formatting the axes and labels
    ax.set_xlabel('$1/L$')
    ax.set_ylabel('Critical Field Amplitude ($H_{c}$)')

    # FIX 2: Increased padding to prevent the title from being cut off
    ax.set_title('Finite-Size Scaling of the Dynamic Phase Boundary', pad=20, fontsize=16)

    # FIX 3: Lock the y-axis bounds to provide proper visual context
    ax.set_ylim(2.0, 5.0)
    ax.set_xlim(left=0)

    # Clean grid and legend
    ax.grid(True, linestyle=':', alpha=0.6)
    ax.legend(loc='lower right', frameon=True, edgecolor='black')

    # 6. Save and display
    plt.tight_layout()
    output_filename = '../data/finite_size_scaling_plot_fixed.png'

    # bbox_inches='tight' ensures the saved file doesn't clip the outer elements
    plt.savefig(output_filename, dpi=300, bbox_inches='tight')

    print(f"Plot successfully saved to: {output_filename}")
    plt.show()

if __name__ == "__main__":
    plot_finite_size_scaling()